IMEI:
  enable: 1
  type: string
  value: ""
SN:
  enable: 1
  type: string
  value: ""
ICCID:
  enable: 1
  type: string
  value: ""
HARDVER:
  enable: 1
  type: string
  value: JWMB1V01
SOFTVER:
  enable: 1
  type: str
  value: 02010001
MODEL:
  enable: 1
  type: int
  value: ""
BLE_MAC:
  enable: 0
  type: string
GSM:
  enable: 0
  type: int
GPS:
  enable: 0
  type: int
SNR:
  enable: 0
  type: int
ADC:
  enable: 0
  type: int
电门:
  enable: 0
  type: bool
外电:
  enable: 0
  type: bool
GSensor:
  enable: 0
  type: bool
ADC_FLAG:
  enable: 0
  type: bool
LOCK:
  enable: 0
  type: bool
RF:
  enable: 0
  type: bool
PWM:
  enable: 0
  type: bool
MUART:
  enable: 0
  type: bool

GPIO:
  enable: 0
  type: io
  value："[0,1,2,3,4,5,6,,10,11,12,13,21,31,32,33,34,36,40,46,47,48]"


