ADC:
  enable: 1
  type: int
  value: 100
ADC_FLAG:
  enable: 1
  type: bool
  value: ""
BLE_MAC:
  enable: 1
  type: string
  value: ""
GPIO:
  enable: 1
  type: io
  value: "[P00,P01,P02,P03,P04,P05,P06,P10,P11,P12,P13,GPIO21,GPIO31,GPIO32,GPIO33,GPIO34,GPIO36,GPIO40,GPIO46,GPIO47,GPIO48]"
GPS:
  enable: 1
  type: int
  value: 30
GSM:
  enable: 1
  type: int
  value: 30
Gsensor:
  enable: 1
  type: bool
  value: ""
HARDVER:
  enable: 1
  type: string
  value: 0201BD10
ICCID:
  enable: 1
  type: string
  value: ""
IMEI:
  enable: 1
  type: string
  value: ""
LOCK:
  enable: 1
  type: bool
  value: ""
MODEL:
  enable: 1
  type: int
  value: ""
MUART:
  enable: 1
  type: bool
  value: ""
PWM:
  enable: 1
  type: bool
  value: ""
RF:
  enable: 1
  type: bool
  value: ""
SN:
  enable: 1
  type: string
  value: ""
SNR:
  enable: 1
  type: int
  value: 30
SOFTVER:
  enable: 1
  type: string
  value: 02010B01
外电:
  enable: 1
  type: bool
  value: ""
电门:
  enable: 1
  type: bool
  value: ""